global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: autocli-daily
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - autocli-daily:8080
